set ref_date = DATEADD("d", - 2, CONVERT_TIMEZONE('Europe/Prague', CURRENT_TIMESTAMP)::DATE)
;

CREATE TABLE "shop_03_complete" AS
SELECT "uni"."shop"
	,"uni"."p_key"
	,"uni"."itemId"
	,"uni"."itemName"
	,"uni"."itemUrl"
  ,"uni"."slug"
	,"uni"."currentPrice"
	,"uni"."originalPrice"
	,"uni"."officialSale"
  ,"uni"."date"
	,"uni"."itemImage"
  ,"uni"."inStock"
	,"ref"."commonPrice"
  ,"ref"."minPrice"
  ,case when "ref"."minPrice" != '' then "ref"."minPrice" else "ref"."commonPrice" end as "originalPriceHS"
  ,round(("uni"."currentPrice" / nullifzero("originalPriceHS") - 1) * -100, 2)  as "newSale"
FROM (select
  "shop"
	,"p_key"
	,"itemId"
	,"itemName"
	,"itemUrl"
  ,"slug"
	,"currentPrice"
	,"originalPrice"
	,"officialSale"
  ,"date"
	,"itemImage"
  ,"inStock"
	FROM "shop_01_unification"
  where left("_timestamp",10) >= $ref_date) "uni"
LEFT JOIN
    (SELECT "itemId"
        , "commonPrice"
        , "minPrice"
        , "date"::varchar as "date"
    FROM "shop_02_refprices") "ref"
ON "uni"."itemId" = "ref"."itemId" AND "uni"."date" = "ref"."date"
;